site_title: Matthew Elsom | Design & Art Direction
site_keywords: matthew, elsom, matthewelsom.com, design, digital, print, art, direction, mobile, applications, identities, corporate, websites, dynamic, html, javascript, singapore, london, tokyo
site_author: Matthew Elsom
site_description: Matthew Elsom | Design & Art Direction. Designing and developing mobile applications, websites, dynamic prototypes and corporate identities in Singapore; with experience managing creative teams in London and Tokyo.

#source: source
#destination: dist
port: 5555

#Google Analytics ID, auto populated to all pages
google_analytics: UA-19247091-2

#URL Prefixing
siteurl: http://matthewelsom.com
baseurl: 

#Permalinks
permalink: none

#Set Syntax Highlighter
highlighter: pygments

#sass import directory
sass:
  sass_dir: assets/_sass
    
#Default Front Matter
defaults:
  -
    scope:
      path: "portfolio" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "portfolio"
      category: "portfolio"
      adv_meta: "yes"
  -
    scope:
      path: "blog" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      category: "blog"
      adv_meta: "yes"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"      