title: Matthew Elsom | Design &amp; Art Direction
keywords: matthew, elsom, matthewelsom.com, design, digital, print, art, direction, mobile, applications, identities, corporate, websites, dynamic, html, javascript, singapore, london, tokyo
author: Matthew Elsom
description: Matthew Elsom | Design & Art Direction. Designing and developing mobile applications, websites, dynamic prototypes and corporate identities in Singapore; with experience managing creative teams in London and Tokyo.
port: 5555

#source: source
#destination: dist

siteurl: 
baseurl: 

permalink: none

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/      
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "portfolio" # previously `post` in Jekyll 2.2.
    values:
      layout: "portfolio"
      category: "portfolio"    
      
#Install Plugins      
